name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  
  BUILD_CONFIGURATION: Ark
  BUILD_VCPKG: Release
  BUILD_PLATFORM: x64
  

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - run:  C:\ProgramData\Chocolatey\bin\vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /t:Build /p:Platform=${{env.BUILD_PLATFORM}} /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:VcpkgConfiguration=${{env.BUILD_VCPKG}}

    - run: mkdir -p x64/Ark/ArkApi/Plugins
    - run: copy "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK\bin\amd64\msdia140.dll " "x64/Ark"

    - uses: actions/upload-artifact@v3
      with:
        name: test-upload
        path: x64/Ark/
